[server]
headless = true
address = "0.0.0.0"
port = 8501
maxUploadSize = 10
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#1d6b4b"
backgroundColor = "#f4f5ec"
secondaryBackgroundColor = "#e8eee1"
textColor = "#13231d"
font = "sans serif"

[theme.sidebar]
primaryColor = "#1d6b4b"
backgroundColor = "#e7eef7"
secondaryBackgroundColor = "#dbe7ef"
textColor = "#04070e"
font = "sans serif"